### PR TITLE
Add metadata to control action execution

### PR DESCRIPTION
**Pull request by wallyworld**
Add extra metadata to actions:
- parallel (does the action need an execution lock)
- execution-group (actions in the same group are serialised on the same lock)

### CODE REVIEW

**Comment by wallyworld** [comment]
[action exec metadata](https://trello.com/c/q9NtUpP3/1333-action-exec-metadata)

**Review by ycliuhw — APPROVED** [review]
lgtm thanks

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
