### PR TITLE
Rename series to supported-series

### PR DESCRIPTION
**Pull request by wallyworld**
Rename the Series attribute in Meta to SupportedSeries.
The Series attribute is not used.

### CODE REVIEW

**Comment by rogpeppe** [comment]
LGTM thanks

**Comment by marcoceppi** [comment]
Is there a reason for the remane? supported-series is so much longer when series: [] achieves the same effect.

**Comment by johnsca** [comment]
I agree.  "series" seems perfectly reasonable to me and I don't understand why we would change this.

**Comment by chuckbutler** [comment]
series: [] seems succinct enough. I'm not following the logic for the rename either.

**Pull request merged**
