### PR TITLE
Use set from the juju/collections package.

### PR DESCRIPTION
**Pull request by howbazaar**
As part of the work to break up juju/utils the set type has moved to juju/collections.

### CODE REVIEW

**Comment by mitechie** [comment]
:shipit:

**Comment by mitechie** [comment]
doh, doesn't look like there's a bot on this. using the big green button and feels scared...

**Comment by rogpeppe** [comment]
@mitechie FWIW the bot in this uses `$$merge$$` not `:shipit:` as it was originally part of the juju-core domain. Wouldn't it be nice to have the same merge instruction everywhere! If in doubt, look at the way that previous PRs have been merged.

**Comment by mitechie** [comment]
@rogpeppe doh, thanks for the clarification

**Pull request merged**
